ci:
    skip: [terraform-fmt, terraform-validate]

repos:

- repo: https://github.com/gruntwork-io/pre-commit
  rev: v0.1.23
  hooks:
    - id: terraform-fmt
      name: Lint Terraform
    - id: terraform-validate
      name: Validate Terraform

- repo: https://github.com/shellcheck-py/shellcheck-py
  rev: v0.9.0.6
  hooks:
    - id: shellcheck

- repo: https://github.com/yelp/detect-secrets.git
  rev: v1.4.0
  hooks:
    - id: detect-secrets
      name: Detect secrets
      args: ['--baseline', '.secrets.baseline']

- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.5.0
  hooks:
    - id: trailing-whitespace
    - id: end-of-file-fixer
    - id: check-yaml
    - id: check-added-large-files
